- hosts: all
  become: yes

  vars:
    MountBase: /mnt
    Partitions:
      - DevFile: loop0
        PartFile: loop0p1
        Number: 1
        Mountpoint: /boot
        Fs: vfat
      - DevFile: loop0
        PartFile: loop0p2
        Number: 2
        Mountpoint: swap
        Fs: swap
      - DevFile: loop0
        PartFile: loop0p3
        Number: 3
        Mountpoint: /
        Fs: ext4

  tasks:
    - name: Mount root filesystem
      mount:
        path: "{{ MountBase }}{{ item.Mountpoint }}"
        src: "UUID={{ hostvars['localhost']['ansible_facts']['devices'][item.DevFile]['partitions'][item.PartFile]['uuid'] }}"
        state: mounted
        fstype: "{{ item.Fs }}"
        fstab: /tmp/fstab
      loop: "{{ Partitions }}"
      when: item.Mountpoint == "/"

    - name: Create mount point
      file:
        path: "{{ MountBase }}{{ item.Mountpoint }}"
        state: directory
      loop: "{{ Partitions }}"
      when: item.Mountpoint != '/' and item.Mountpoint != 'swap'

    - name: Mount filesystem other /
      mount:
        path: "{{ MountBase }}{{ item.Mountpoint }}"
        src: "UUID={{ hostvars['localhost']['ansible_facts']['devices'][item.DevFile]['partitions'][item.PartFile]['uuid'] }}"
        state: mounted
        fstype: "{{ item.Fs }}"
        fstab: /tmp/fstab
      loop: "{{ Partitions }}"
      when: item.Mountpoint != '/' and item.Mountpoint != 'swap'

    - name: Execute pacstrap
      shell: "pacstrap {{ MountBase }} base linux linux-firmware ansible"

    - name: Generate fstab stage1
      shell: "genfstab -U {{ MountBase }} | grep -v swap > {{ MountBase }}/etc/fstab"

    - name: Generate fstab stage2
      shell: "echo -e 'UUID={{hostvars['localhost']['ansible_facts']['devices'][item.DevFile]['partitions'][item.PartFile]['uuid']}}\tnone\tswap\tdefaults\t0 0' >> {{ MountBase }}/etc/fstab"
      loop: "{{ Partitions }}"
      when: item.Fs == "swap"

    - name: Make password
      shell: mkpasswd -m sha-512
      register: pw

    - name: Set password for stage3
      lineinfile:
        path: stage3.yml
        regexp: '^    AdminUserPassword:.*$'
        line: "    AdminUserPassword: {{pw.stdout}}"

    - name: Push stage3.yml
      copy:
        src: stage3.yml
        dest: "{{MountBase}}/root/"
        mode: 0600